### ISSUE TITLE
bower install fail with three file cannot download

### ISSUE THREAD

**Issue by metroroland** [dobtco/formbuilder#102]
I tried to have a fresh install. When I run `bower install`,  it start to download most file, but there are no progress for `https://gist.github.com/adamjacobbecker/8902451/raw/b68459289526cb76c2e22416d98d0dbd0b722fa0/ie8_node_enum.js`
`https://gist.github.com/adamjacobbecker/6519570/raw/cd741057495d0fb19e545a0f9a098efba3bef9c8/jquery.scrollWindowTo.js` and
`https://gist.github.com/adamjacobbecker/6519561/raw/63682037af9b10200b05c1a3d5890903397b2103/underscore.mixin.deepExtend.js`. It return a 404 message and the installation is interrupted.

I tried to go adamjacobbecker's page , but it is shut down already. Should formbuilder move to other dependancies?

**Comment by fmkoba** [comment]
Same issue here.
