### ISSUE TITLE
How to update  bootstrapData: ?

### ISSUE THREAD

**Issue by mustaqsheikh** [dobtco/formbuilder#103]
How do I update  bootstrapData: value each time the form is changed ?

``` javascript
fb = new Formbuilder({
  selector: '.fb-main',
  bootstrapData: [{"field_type": "date", "required": true, "label": "Date", "field_options": {}, "cid": "date0"}]
});
```

If anyone knows, please provide an example code, thanks

**Comment by siddarth-rajavelu** [comment]
$(function () {
            var initFormData;
            $.ajax({
                url: 'Home/GetFileFromDisk',
                async: false,
                success: function (result) {
                   var temp = JSON.parse(result);
                    initFormData = temp.fields;
            },

```
        });
        fb = new Formbuilder({
            selector: '.fb-main'
            ,bootstrapData: initFormData
        }, function () { alert(JSON.stringify(initFormData));});
```

**Comment by ajb** [comment]
This data is designed to be persisted in a database.
