### ISSUE TITLE
Creating new form components or removing options with existing ones

### ISSUE THREAD

**Issue by savyk** [dobtco/formbuilder#109]
Is there a way to create new form components by passing in its configuration via javascript, such as to make a slider component?   

Also, is there a way to remove mappings for existing components via javascript, such as to tell the plugin to not render the 'Admin Only' option?

**Comment by ajb** [comment]
Hi there,

There is not currently an API for this, so you'll have to tweak the source. Unfortunately, I think that adding APIs for all of the possible configuration options would be untenable.
