### ISSUE TITLE
Attach other elements to save button

### ISSUE THREAD

**Issue by savyk** [dobtco/formbuilder#126]
I have created a new tab on the formbulider to house form information such as title and description.  However I can't figure out how to attach those new fields (one input and one textarea) defined  in my new file -> templates/partials/edit_form.html <- to the handleFormUpdate method in order to toggle the save button upon change.  Could I get some guidance in doing this?

**Comment by csimpi** [comment]
What was the solution?

**Comment by abrarazeem** [comment]
What was the solution?
