### ISSUE TITLE
Is it possible to load a form template into the formbuilder from existing JSON?

### ISSUE THREAD

**Issue by jordancalder** [dobtco/formbuilder#131]
Once a form is saved, is it possible to come back to the formbuilder and load in that form for further editing?

**Comment by apopp72** [comment]
1 - You capture the JSON structure to save the form in the database:
       Ex: JSON.stringify (fb.mainView.collection.toJSON ())

2 - You can recover the structure of the database and inject back
       Ex: fb = new FormBuilder ({
                     selector: '.fb-main',
                     bootstrapData: JSON.parse (jsonStructure)
              });

**Comment by suyash248** [comment]
@apopp72  - It worked. Thanks.
