### ISSUE TITLE
JQuery UI Dialog

### ISSUE THREAD

**Issue by rfouty** [dobtco/formbuilder#149]
I'm trying to add a dialog to confirm deleting and i'm getting an error in the vendor.js file.  Is there a possible conflict with this library?

**Comment by smurfpandey** [comment]
What error are you getting?

**Comment by rfouty** [comment]
I figured it out, I had the load order incorrect between JQuery UI and vendor.js.  Originally I had JQueryUI then vendor & formbuilder.js.  After I switched the order and placed the vendor and formbuilder.js first the dialogue control started to work.  Rookie mistake!
