### ISSUE TITLE
Document Data Format

### ISSUE THREAD

**Issue by bitmage** [dobtco/formbuilder#15]
Hey, could you add some documentation on the format of the data output?  Some examples would be handy too.  The UI looks nice, the data format is my last remaining question.  :-)

**Comment by ajb** [comment]
Yep. I'm working on making the data format customizable, too. (it's on a feature branch if you want to take a look.)

For now, you should be able to inspect the output in the console.

**Comment by bitmage** [comment]
Perfect, that's just what I was looking for.

I just created a form renderer as a twitter flight component:

https://github.com/torchlightsoftware/flight-forms

As I suspected, our data formats are somewhat similar.  If you're interested, we could work to synch up the data formats so the tools would interop well.

Edit:

Here's some example data from mine:

https://github.com/TorchlightSoftware/flight-forms/blob/master/data/name-form.coffee

Other examples are in the data folder.
