### ISSUE TITLE
Working with php-mysql

### ISSUE THREAD

**Issue by bencagri** [dobtco/formbuilder#154]
I'm trying to get json data (using php) from database for bootstrapData. But fb does not show fields. Returned json is;

```
             var form_inputs = '[<?php echo $extra->forms; ?>]';
              console.log(form_inputs);
                  $(function(){
                    fb = new Formbuilder({
                      selector: '.fb-main',
                      bootstrapData:  form_inputs
                    });

                    fb.on('save', function(payload){
                      $('#form_input').val('');
                      $('#form_input').val(payload);
                     // console.log(payload);
                    })
                  });
```

form_inputs returns this;

 [{"fields":[{"label":"Sessions","field_type":"dropdown","required":false,"field_options":{"options":[{"label":"1","checked":false},{"label":"2","checked":false},{"label":"3","checked":false},{"label":"4","checked":false}],"include_blank_option":false},"cid":"c6"}]}]

but somehow, fb does not show fields. Is there anything that i miss?
P.S: When i try to add some fields, it combines form_inputs json with new generated json. But still no inputs showing (except new added)

**Comment by bencagri** [comment]
Okay solved. 
While saving database;

```
        JSON.stringify(payload);
```

getting json from database;

```
        bootstrapData:  JSON.parse(obj)
```

thats it.

**Comment by rejani** [comment]
hi bencagri,
i have tried with same ... but i cannot display the form ... how did you display form usin the above json code.

in DB  
"{\"fields\":[{\"label\":\"name\",\"field_type\":\"text\",\"required\":true,\"field_options\":{\"size\":\"small\",\"description\":\"names\"},\"cid\":\"c2\"}]}"

**Comment by bencagri** [comment]
You should use JSON.parse() function.  

```
            $forms = $db->forms;  //do db staff here get your json value
             var form_inputs = '[<?php echo $forms; ?>]';
             $(function(){
                fb = new Formbuilder({
                  selector: '.fb-main',
                  bootstrapData:  JSON.parse(form_inputs) //your problem is here
                });

                fb.on('save', function(payload){
                  $('#form_input').val('');
                  $('#form_input').val(payload);
                 // console.log(payload);
                })
              });
```

**Comment by suyash248** [comment]
Hi rejani,
I'm facing same problem as you did. Could you please help me out?

I have following string stored in DB - 
"{\"fields\":[{\"label\":\"City\",\"field_type\":\"text\",\"required\":true,\"field_options\":{\"size\":\"small\"},\"cid\":\"c2\"}]}"

I fetch this in my JS function and have it like this - 
var payloadString = '"{\"fields\":[{\"label\":\"City\",\"field_type\":\"text\",\"required\":true,\"field_options\":{\"size\":\"small\"},\"cid\":\"c2\"}]}"';  // Note it's inside single quotes.

**Comment by arirah** [comment]
var form_data = {"fields":[{"label":"Google API","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c14"},{"label":"Do you have a website?","field_type":"website","required":false,"field_options":{"description":"vinnorokom.com"},"cid":"c1"},{"label":"Please enter your clearance number","field_type":"text","required":true,"field_options":{"description":"12109212"},"cid":"c6"},{"label":"Security personnel #82?","field_type":"radio","required":true,"field_options":{"options":[{"label":"Yes","checked":false},{"label":"No","checked":false}],"include_other_option":true},"cid":"c10"},{"label":"Medical history","field_type":"file","required":true,"field_options":{},"cid":"c14"}]} ; 

I saved this json to mysql then use like this 

 fb = new Formbuilder({
        selector: '.fb-main',
        bootstrapData:  JSON.parse(form_data) 
      });

But not working .. can you help me ??

**Comment by SteveChurch** [comment]
I'm not at s computer at the moment but will give you a reply in a few days

**Comment by arirah** [comment]
Ok .. but need a quick solution plz ..

**Comment by SteveChurch** [comment]
Sorry bad accident with a friend won't be a few days.

**Comment by arirah** [comment]
I am still waiting for solution

**Comment by bencagri** [comment]
Seems like problem is here:

var form_data = {"fields":[{"label":"Google API","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c14"},{"label":"Do you have a website?","field_type":"website","required":false,"field_options":{"description":"vinnorokom.com"},"cid":"c1"},{"label":"Please enter your clearance number","field_type":"text","required":true,"field_options":{"description":"12109212"},"cid":"c6"},{"label":"Security personnel #82?","field_type":"radio","required":true,"field_options":{"options":[{"label":"Yes","checked":false},{"label":"No","checked":false}],"include_other_option":true},"cid":"c10"},{"label":"Medical history","field_type":"file","required":true,"field_options":{},"cid":"c14"}]} ;

try put data between single quote ( ' ). or try brackets.. Like my second answer https://github.com/dobtco/formbuilder/issues/154#issuecomment-90607231

**Comment by arirah** [comment]
Are you talking about  var form_inputs = '[<?php echo $forms; ?>]'; this line ?? 

Let me check !

**Comment by arirah** [comment]
var form= [{"fields":[{"label":"Untitled","field_type":"text","required":true,"field_options":{"size":"small"},"cid":"c2"}]}]; 

Not working

**Comment by smurfpandey** [comment]
Use this instead:

``` javascript
fb = new Formbuilder({
selector: '.fb-main',
bootstrapData: JSON.parse(form_data).fields 
});
```

Working JSbin example: http://jsbin.com/jusurolocu/edit?html,css,js,output

**Comment by arirah** [comment]
Thanks @smurfpandey .. Let me check.

**Comment by arirah** [comment]
YES you are right !  @smurfpandey . it is working .. Thank you very much

**Comment by smurfpandey** [comment]
@bencagri Can you close this issue?
