### ISSUE TITLE
How do I send the saved data to server in json form ?

### ISSUE THREAD

**Issue by zurez** [dobtco/formbuilder#157]

**Comment by suyash248** [comment]
Inside index.html (I'm working on Java web app. So I changed it to index.jsp), You will find following callback- 
fb.on('save', function(payload){
  console.log(payload);
}

So here you need to write code to send the data to server, as follows - 
fb.on('save', function(payload){
  console.log(payload);
  $.post(url, 
            { 
                payload: payload
            }, 
            function(response){
                // If you want to perform some task using response, Do it here.
            }
  );
}

**Comment by SteveChurch** [comment]
Did you get this solved or require any further support?

**Comment by zurez** [comment]
Thanks for the reply. I just saw it. I will check it out. 
Also is it possible to convert this into something like typeform? How hard it will be and what files do I need to change?

**Comment by vidhyabala** [comment]
Can anyone help me...
I need to create a field as same as the address field....when i duplicate the field i cant able to edit the html what we defined in script
