### ISSUE TITLE
Drag & Drop Sort Order

### ISSUE THREAD

**Issue by SteveChurch** [dobtco/formbuilder#160]
I'm a little confused and can not seem to find any information about this. When you drag and drop to move the ordering of your fields no data is stored in JSON to reflect this? If this a bug or a oversight on my side? - Why allow drag and dropping of field ordering if it does nothing?

**Comment by SteveChurch** [comment]
Closing this, I will work on a solution and commit.

**Comment by NormanEdance** [comment]
I know it's been while ago, but what kind of workaround it was? There's no events for drag'n'drop or smth to work with.
