### ISSUE TITLE
Can't use this integration

### ISSUE THREAD

**Issue by prakhar888v** [dobtco/formbuilder#169]
I am new to this technology.
Can you please give step-by-step procedure to integrate this in my web-application.
I am not familiar with npm and node.

**Comment by smurfpandey** [comment]
You check this https://github.com/dobtco/formbuilder/blob/gh-pages/index.html

**Comment by SteveChurch** [comment]
As @smurfpandey has mentioned you can see the example of this project, however could you please share more information about your integration and we can help you with implementing this or at least point you in the right direction with integration with databases, storing, retrieving and more.

**Comment by prakhar888v** [comment]
Everything good now.
Implemented it without any issues.

**Comment by SteveChurch** [comment]
@prakhar888v excellent, could you please close this issue. 

Thank you
