### ISSUE TITLE
Save problem again...

### ISSUE THREAD

**Issue by Patatou** [dobtco/formbuilder#170]
Hi,

I want to save form content into data base, but i want give the name of database entry in parameter.

Try to do this, but not find...

Help welcome :'(

**Comment by Patatou** [comment]
Or/And, how can i get the content form outside formBuilder.js (like method) ?

**Comment by smurfpandey** [comment]
Step 1: Implement a handler for save event https://github.com/dobtco/formbuilder#save
Step 2: Call save method on the formbuilder object as `builder.saveForm();`

**Comment by Patatou** [comment]
perfect ty !

**Comment by Arya18** [comment]
@smurfpandey Could you please tell me that where it has started the initialization of draggable jquery event. 
I want to achieve multi column functionality so that I can drop multiple elements in a single row.
