### ISSUE TITLE
Formbuilder and jquery

### ISSUE THREAD

**Issue by Patatou** [dobtco/formbuilder#171]
Hi,

I'm using formbuilder with some other module requiert Jquery (like Fullcalendar, bootstrap...), and when place .js after all other, i've error like 'Tooltip is not a function' or 'fullcalendar is not a function'.

But, when i put formbuilder.js before the other, it doesn't work (drag and drop work, but nothing appear)....

Any idea ?

Ty

**Comment by Patatou** [comment]
It's like that :
< script type="text/javascript"  src='../fullcalendar/lib/jquery.min.js'></script>

< script type="text/javascript"  src='../fullcalendar/lib/moment.min.js'></script>
< script type="text/javascript"  src='../fullcalendar/fullcalendar.min.js'></script>
< script type="text/javascript"  src='../fullcalendar/lang-all.js'></script>

< script type="text/javascript"  src='../js/bootstrap.js'></script>
< script type="text/javascript"  src='../js/jquery-ui.js'></script>

< script type="text/javascript"  src='../js/datepicker-fr.js'></script>

< script type="text/javascript"  src="../js/_main.js"></script>

< script type="text/javascript" src="../js/tablesorter/jquery.tablesorter.js"></script> 
< script type="text/javascript" src="../js/tablesorter/jquery.tablesorter.widgets.js"></script>
< script type="text/javascript" src="../js/tablesorter/widgets/widget-scroller.js"></script>
< script type="text/javascript" src='../js/tablesorter/widgets/widget-filter-formatter-jui.js'></script>
< script type="text/javascript" src='../js/tablesorter/widgets/widget-editable.js'></script>
< script type="text/javascript" src='../js/jquery.colorPicker.js'></script>

< script type="text/javascript" src="../js/formbuilder/vendor/js/vendor.js"></script>
< script type="text/javascript" src="../js/formbuilder/dist/formbuilder.js"></script>

**Comment by Patatou** [comment]
Ok then, when i do this :+1: 
jQuery.noConflict();
    (function( $ ) {
      $(function() {
                var formbuilder = new Formbuilder({ selector: '#formbuilder' });
     });
    })(jQuery); 

Everything fine...

**Comment by smurfpandey** [comment]
vendor.js already includes jquery, that might be causing the issue.

**Comment by Patatou** [comment]
My solution is good, no ?
