### ISSUE TITLE
Desactivate Jquery lib in vendor.js

### ISSUE THREAD

**Issue by Patatou** [dobtco/formbuilder#173]
Hi,

How can i desactivate Jquery Lib use in Vendor.js (because I already include it in my file) ?

When I use "noconflict" option, I can't use some tools in "noconflict" pragma like tooltip or dialog.

Ty

**Comment by smurfpandey** [comment]
Instead of using vendor.js, you can manually add all the dependencies. Check bower.json for dependencies
https://github.com/dobtco/formbuilder/blob/gh-pages/bower.json#L21

**Comment by Patatou** [comment]
Gonna try right now.

Ty

**Comment by smurfpandey** [comment]
@Patatou Did it work for you? If yes, please close this issue.
