### ISSUE TITLE
instructions: allow for multiple paragraphs and rich text

### ISSUE THREAD

**Issue by drewda** [dobtco/formbuilder#18]
When form creators want to include instruction text, looks like the only option available to them at the moment is a section break with a small amount of text. How about allowing longer amounts of text, with paragraph breaks and rich formatting (well, at least bold and italics)? Maybe with Markdown formatting?

**Comment by ajb** [comment]
Interesting... right now I'm just passing it through the `simple_format` helper which converts newlines to `<br>`s.

I'm not really a fan of adding a markdown parser to the list of dependencies, but we could allow HTML and just render it that way. Formbuilder's users, in my mind at least, aren't the kinds of folks who know Markdown.

**Comment by drewda** [comment]
I'm also leery of suggesting that non-technical users learn Markdown, but
I've run into so many issues in the past with CKEditor and similarly
weighty WSYWIG editor libraries that I'm almost thinking it's worth asking
users to at least learn the Markdown syntax for bold and italics.

**Comment by ajb** [comment]
Closing this -- you're free to implement it server-side however you'd like, and as it is, Formbuilder supports HTML in the field descriptions. Let me know if you think I've missed anything.

**Comment by drewda** [comment]
Sounds good. Thanks, @adamjacobbecker
