### ISSUE TITLE
Loading existing JSON

### ISSUE THREAD

**Issue by nikkobautista** [dobtco/formbuilder#19]
Is there a way to load an existing JSON form configuration? E.G., I save the built forms into my DB, then the user can edit it and it will load the form again.

**Comment by nikkobautista** [comment]
Ah ignore this, I just saw the example with "bootstrapData". Thanks!

**Comment by reru** [comment]
Hi, I would like to do the same thing, but I can't make it work. How did you do it? Thank you very much.

**Comment by reru** [comment]
Ignore my comment. Got it. Thank you.
