### ISSUE TITLE
Dissabling "autosave"

### ISSUE THREAD

**Issue by nikkobautista** [dobtco/formbuilder#20]
Is there an option for disabling this? I only want it to save whenever the button is clicked.

**Comment by ajb** [comment]
No option currently. I'll leave this open and try to add this in, as it seems like a good option to have.

**Comment by aviatrix** [comment]
any updates on this ?

This is definitely something that should be integrated as soon as possible.

**Comment by jzapanta-anselm** [comment]
Commenting out this line 276-278 (approximately) on formbuilder.js appears to "disable" autosave as a workaround:

setInterval(function() {
        return _this.saveForm.call(_this);
      }, 5000);

**Comment by RubSar** [comment]
In  Formbuilder.options change AUTOSAVE: true to false
