### ISSUE TITLE
Live mode

### ISSUE THREAD

**Issue by adityagodbole** [dobtco/formbuilder#21]
Hi,
I'm not sure how to start a discussion thats neither an improvement request or a bug, so just creating an "issue".
I have forked formbuilder to add a "live" mode where you can render the form such that it can be filled in by a user and submitted. I've been hacking at this for a couple of days and the changes will probably a bit rough around the edges. I would like any feedback on whether the changes are desirable and any opinion on the code if they are. https://github.com/adityagodbole/formbuilder

**Comment by ajb** [comment]
Thanks for opening this issue -- this seems like a feature that if you're ok with rendering your forms via javascript, is great to have.

I've taken a look at the changes in your fork. What do you think of subclassing `Formbuilder` to something like `LiveFormbuilder`? If you did that, I would have no problem merging this into master. As it stands, the code is a little intrusive for me.

Serious :thumbsup: though -- hope we can get this in :)

**Comment by adityagodbole** [comment]
I'm currently making changes in order to get it working for my project at work. I'll get down to refactoring it into a separate class once it's working fine internally.

**Comment by stephentcannon** [comment]
Did anyone ever accomplish this?

**Comment by stephentcannon** [comment]
@adityagodbole Did you ever build the live mode rendering methods?  or attempt to?  I am interested to see what you have done or tried before I give it a shot.

**Comment by adityagodbole** [comment]
Yes, I have added this feature and implemented a lot more functionality in it as well. Unfortunately, due to time constraints I have some project specific functionality mixed in. I am in the process of refactoring and optimising the code, but it is going very slow. If you can email me at code.aa at gdbl dot me from your email address, I could describe it in more detail and maybe even give you access to the private repo. I just don't want to discuss it here until I push my changes back to the public repository, which, I hope will be soon.

**Comment by stephentcannon** [comment]
@adityagodbole thank you for the reply.  I integrated formbuilder into a Meteor.js project so instead of using formbuilder for the live rendering to the customer I just used Meteor spacebars ( handlebars for for real-time rendering and reactivity).  It ended up being a much easier and quicker solution that only took about 30 minutes.  Thank you for getting back to me though.
