### ISSUE TITLE
Load an already created form into FormBuilder

### ISSUE THREAD

**Issue by chirag-recognite** [dobtco/formbuilder#230]
I have the data one gets in JSON format when a form is created. What if the user wishes to open a previously created form and further edit it? How does one go about doing that? Which function or component in FormBuilder.js does one need to work with?

**Comment by max-kk** [comment]
Hi,

Here is some code example:

```php
        <div class='fb-main'></div>

        <script>
            $(document).ready(function() {
                var fb = new Formbuilder({
                    selector: '.fb-main',
                    bootstrapData: jQuery.parseJSON('<?php echo $form->fields; ?>'),
                });

                Formbuilder.options.HTTP_ENDPOINT = "<?php echo add_query_arg('form_id',$form->ID, wp_nonce_url( admin_url('admin-ajax.php') )); ?>";
                Formbuilder.options.HTTP_SAVE_ACTION = "fv_save_form_structure";
                Formbuilder.options.HTTP_RESET_ACTION = "fv_reset_form_structure";
                Formbuilder.options.HTTP_METHOD = "POST";
            });
        </script>
```

**Comment by chirag-recognite** [comment]
BuilderView.prototype.initialize = function(options) {
      var selector;
      selector = options.selector, 
      this.formBuilder = options.formBuilder, 
      this.bootstrapData = options.bootstrapData;
      if (selector != null) 
      {
        this.setElement($(selector));
      }
      this.collection = new FormbuilderCollection;
      this.collection.bind('add', this.addOne, this);
      this.collection.bind('reset', this.reset, this);
      this.collection.bind('change', this.handleFormUpdate, this);
      this.collection.bind('destroy add reset', this.hideShowNoResponseFields, this);
      this.collection.bind('destroy', this.ensureEditViewScrolled, this);
      this.render();
      this.collection.reset(this.bootstrapData);
      return this.bindSaveEvent();
    };

This is the new code and I am creating a meanJS application. Based on your code it seems like I have to send data into this function by options.bootstrapData.
