### ISSUE TITLE
Improve build process and distribution

### ISSUE THREAD

**Issue by hijonathan** [dobtco/formbuilder#25]
First off, thanks for creating a cool project. I've generally had good luck with it and patched it where I could with pull requests. After spending some time with it, I think the following improvements would be really helpful:
- [x] Stricter adherence to a package system (`npm`, `bower` or `component`).
- [x] Reliable declaration of `main` for amd/commonjs peeps.
- [x] Better dependency versioning (and a good process for locking versions).
- [x] Modularized Backbone components instead of one big `main.coffee` file. Views would be a great place to start.
- [x] Basic tests, even one that just checks that initialization works.

**Comment by drewda** [comment]
Nice set of suggestions for building a more mature library, @hijonathan.

With respect to modularizing Backbone code, I've had good luck with the various pieces that [Marionette](http://marionettejs.com/) offers for views, business logic, messaging, etc.

**Comment by ajb** [comment]
Yes, thanks @hijonathan for all of your work with these PRs and issues! It might take me a couple days to address them all, but some quick thoughts:
- Let's use bower.

Actually fuck it, I agree with everything on your list.

**Comment by hijonathan** [comment]
:thumbsup: 

Glad you agree. This is a cool library, it just needs a bit of straightening up. I'm considering using it for a project of mine, and I'll submit fixes as I come to them.

**Comment by ajb** [comment]
Agreed -- originally I didn't think this was something that I'd be able to extract out of our apps, so I think a lot of the deficiencies probably come from areas where it's too opinionated or something. Also has a ton of deps.

Anyway, you now have commit to this repo. Use it sparingly :)

**Comment by hijonathan** [comment]
Ballin!

**Comment by hijonathan** [comment]
These have been addressed in the forthcoming `0.2.0` milestone.
