### ISSUE TITLE
Not work on IE8

### ISSUE THREAD

**Issue by imhazige** [dobtco/formbuilder#32]
Hi, I have found a library to make the user be able to build form via drag and drop, this project is prefect, but have some problem to integrate to my app.

When I test on IE9, it works, ok, but for IE8, it not work, can you make it support IE8? As there are lots of users of our app is still using ie8.

And We are using bootstrap, hope this will work fine within bootstrap. 

Good jobs and Thanks.

**Comment by ajb** [comment]
Hi,

Thanks for opening this issue. IE8 was not something I was targeting, but I'd be happy to look into why it's not working.

Can you provide any more info? Does it not render at all? Or do certain features not work?

**Comment by zeroven** [comment]
![image](https://f.cloud.github.com/assets/1636635/1972169/551a74ca-8343-11e3-99cf-43478316263d.png)
Error such as imges up!

**Comment by zeroven** [comment]
In verdor.js   line 834
        document.addEventListener( "DOMContentLoaded", completed, false );
line 837  
window.addEventListener( "load", completed, false );

IE8   not supported

**Comment by zeroven** [comment]
![image](https://f.cloud.github.com/assets/1636635/1972287/9a53c440-8345-11e3-8df5-4c0af3ed3c08.png)

 the following lists is not supported in IE 8  : 
jQuery.now()
jQuery.isArray
window.getComputedStyle()
key.concat( key.map( jQuery.camelCase ) );

**Comment by aviatrix** [comment]
@Zeroven,

Try editing vendor.js manually, remove the jquery that is bundled with it and add an older version of jQuery maybe 1.6 will work.

**Comment by zeroven** [comment]
@aviatrix thks

**Comment by zeroven** [comment]
@aviatrix do you have an IE's supported version?  and would you please make one targ and push it?
 If not, I will modified one targ version for IE later
CC @adamjacobbecker

**Comment by ajb** [comment]
Hey guys, happy to review and merge any PRs that come out of this, but IE8 compatibility is not something I'm going to be able to work on myself.

**Comment by zeroven** [comment]
@adamjacobbecker Hi,IE8 compatibility on my local machine is now work well!  if U update a new version fixed this issue. Give me a msg please.

I use jquery 1.8.3  ,then  add IE's events binding method to fix the issue

**Comment by ajb** [comment]
A pull request would be much appreciated. Until then, I'm going to close this issue. Thanks!

**Comment by gsxdsm** [comment]
@zeroven Did you ever submit a PR for this?
