### ISSUE TITLE
Submit button?

### ISSUE THREAD

**Issue by ericabiz** [dobtco/formbuilder#35]
We're looking at using this and I was curious about the lack of a submit button option. When enabling users to build their own forms, it seems as if it would make sense for them to be able to build their own submit button, align it left/right/center, and change the text and color. 

Is there a reason this isn't in there? (I'm happy to pull request it should we use this project, but was wondering what the design decision/thought behind this was.)

Thanks!
-Erica

**Comment by ajb** [comment]
No reason. Go for it!

**Comment by ericabiz** [comment]
Cool--thank you for the quick response!
