### ISSUE TITLE
How to Add ID for once attibute

### ISSUE THREAD

**Issue by jojoluzifer22** [dobtco/formbuilder#37]
etc,

<input type="text" id="1">

![untitled-2](https://f.cloud.github.com/assets/5371533/1804610/a377a95a-6c5d-11e3-87c2-29add3351a9d.png)

i want to add ID this 

Could you advice me to do that

**Comment by JSlote** [comment]
It's a backbone.js thing. Google "backbone cid"

**Comment by JSlote** [comment]
Also, this is not an issue

**Comment by jojoluzifer22** [comment]
Sorry , I'm start to load this and i have no idea what it's .

**Comment by ajb** [comment]
I'm sorry, we can't help you if you completely change your question instead of closing it and opening a new one.

As far as adding an ID attribute goes, you could add an input field here: https://github.com/dobtco/formbuilder/blob/gh-pages/src/templates/edit/common.html that asks for an ID.
