### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by JakeAustwick** [dobtco/formbuilder#38]
Apologies in advance as I'm pretty sure it's me not used to grunt development, but I can't seem to get my head around how you have it all setup.

I've downloaded the repo, installed the npm and run the bower command.

Now if I run `grunt watch`, I just get:

```
Running "watch" task
Waiting...%
```

I've tried running the other grunt commands, but I just can't seem to get my changes reflected in index.html. Am I supposed to change which JS file the index.html file points to?

Any guidance appreciated.

**Comment by JSlote** [comment]
Hey Jake, I ran into the same problem and filed an issue a couple days ago: https://github.com/dobtco/formbuilder/issues/36

The gruntfile is in fact broken. My fork has a fixed version if you'd like to clone it instead: https://github.com/JSlote/formbuilder

If you'd rather just replace the gruntfile and start developing on the main repo, here's the fixed gruntfile blob: https://github.com/JSlote/formbuilder/blob/c3950257248256f7e6f4c42e440299b0a8df6dfe/Gruntfile.coffee

You'll also need to add the following line to your package.json in devDependencies:
`"grunt-contrib-clean": "~0.4.0",`

**Comment by JakeAustwick** [comment]
Perfect, I'm using your fork :)

**Comment by ajb** [comment]
i'll work on fixing the gruntfile in this main repo.
