### ISSUE TITLE
remove jquery ui dependency?

### ISSUE THREAD

**Issue by ajb** [dobtco/formbuilder#4]
http://farhadi.ir/projects/html5sortable/

**Comment by ajb** [comment]
https://github.com/yields/sortable

**Comment by ajb** [comment]
not happening at the moment

**Comment by drewda** [comment]
@adamjacobbecker, I'm just starting to learn my way around the formbuilder code and am curious to know, is the drag-and-drop sortable list the only place where jQuery UI is used?

**Comment by ajb** [comment]
yes sir.
