### ISSUE TITLE
Mouse pointer place on rtl drag

### ISSUE THREAD

**Issue by amirpaia** [dobtco/formbuilder#40]
I change direction of form builder and now i drag field from right panel to left panel. Drag & drop is Ok but my problem is [position of mouse pointer and position of box while] dragging. On start dragging, draggable box placed right of mouse pointer whereas I want item placed on left side of mouse pointer. 

I found draging item is a div with "response-field-draggable-helper" class. Position of this div change with mouse move. On mouse move set Top and Left of this div and to solve my problem should set Top and Right but how? I try couple hours and unsuccessful !
can help me a guy? 
Tnx

**Comment by ajb** [comment]
Can you provide a screenshot or screencast? I'm having trouble understanding your first paragraph.

Thanks!

**Comment by amirpaia** [comment]
Please see this screenshot.
![formbuilder](https://f.cloud.github.com/assets/1608298/1826169/e17fdcce-71ec-11e3-90ca-eb9f51fe2c79.jpg)

sorry for my english. (:

**Comment by ajb** [comment]
Hi @amirpaia, I hope you've figured this out. Sorry I couldn't be of more help.
