### ISSUE TITLE
Override Templates

### ISSUE THREAD

**Issue by AkaAnto** [dobtco/formbuilder#41]
Hi, love your formbuilder, is really amazing. I would like to know where or how can i overrride the given templates for customization. A simple example would be great, greetings and congratulations on your great work.

**Comment by JSlote** [comment]
**If you're talking about customizing the fields:**

You currently have to just edit the fields in `src/scripts/fields/`

If you would like to disable certain fields, my fork (https://github.com/JSlote/formbuilder) has added that functionality.

**If you're talking about customizing the DOM:**

The templates are in `src/templates/`

**Comment by ajb** [comment]
Yeah -- I've been thinking a lot about this plugin, and how far to go WRT customization. 

My current inclination is to remove a lot of these customization features from the codebase, and instead let folks fork the library and modify it for their specific needs. There's no way we'll be able to cover every use case with configuration options alone, and once you start making everything "dynamic", it's easy for a codebase to get bloated and ugly.

So yeah, @JSlote is correct, I would fork the repo and start hacking in the `src/scripts/fields` directory. If you want to disable a field, you should just be able to remove the appropriate file.

**Comment by AkaAnto** [comment]
Thank you guys for your quick response. And yeah, i am interested in both cases (DOM and fields customization). I tried what you said before making the question but nothing seems to change, i made changes on the templates and it didnt have and effect. Let try it again and check your repo for ilumination. Thanks again guys.

**Comment by AkaAnto** [comment]
Sorry but i dont seem to get it working. I dont have much experience with coffeescript, for what i know (probably wrong) i modify the files in src/scripts/fields and then run coffee --watch --compile *.coffee inside  src/scripts/fields . This compiles all files but when i re run the index.html file nothing seems to change. Is there a step i am missing ?. Thkans for your time and sorry again.

**Comment by ajb** [comment]
you'll have to run `grunt dist` to build the concatentated & minified files required in `index.html`, or change the links in `index.html` to references the non-minified assets.

**Comment by AkaAnto** [comment]
Hey man, thanks for your reply. I think I am missing the big picture here because im dealing with a lot of new (for me) js tech and I still dont know most off what i am doing here. Until now I have done the following in order to change  the add  new field tap label t to "Add Field"  without success:
1) Downloaded this repo.
2) Open File src/templates/partials/left_side.html and edited it so it look like this:

<div class='fb-left'>
  <ul class='fb-tabs'>
    <li class='active'><a data-target='#addField'>Add Field</a></li>
    <li><a data-target='#editField'>Edit field</a></li>
  </ul>
  <div class='fb-tab-content'>
    <%= Formbuilder.templates['partials/add_field']() %>
    <%= Formbuilder.templates['partials/edit_field']() %>
  </div>
</div>

Then i open index.html in my browser and nothing changes. Then i notes this notation im not familiar with <%= Formbuilder.templates['view/label']({rf: rf}) %>  in google it without success. After i tried with the "src/scripts/fields/" files editing im didnt success either. So, I know the real problem is me being a noobster in js, so is there possible you tell me what should i do or investigate in order to customize both the DOM and the Fields. Thanks for your time.

**Comment by AkaAnto** [comment]
I Dont know why the html i paste in step 2 is missing, anyway i just change one phrase for another in such file.

**Comment by JSlote** [comment]
You will not see changes in your browser until the templates are processed by Grunt (worth a google), a popular Node.js task runner. It converts coffeescript to js, concatenates files, minifies the combined source, etc. All grunt commands are run in the working directory of the project. I.e. not in a particular folder like `src` or `dist`. Just follow the instructions in the bottom of the readme and run `grunt` alone before you run `grunt watch`

From: Antonio Rodriguez
Sent: ‎Sunday‎, ‎January‎ ‎5‎, ‎2014 ‎4‎:‎03‎ ‎PM
To: dobtco/formbuilder
Cc: Joseph Slote

I Dont know why the html i paste in step 2 is missing, anyway i just change one phrase for another in such file.

**Comment by AkaAnto** [comment]
Thanks for your answer, i ll do what you say.

**Comment by AkaAnto** [comment]
Finally got it working, it turns out among other things my bower wasnt working properly. Now I have a better understanding of how this type of project (npm/bower/grunt) works and that made me love it even more.  Thanks again for your responses and patience.
