### ISSUE TITLE
Documentation is somewhat rudimentary

### ISSUE THREAD

**Issue by ddokter** [dobtco/formbuilder#43]
Some examples of typical use-cases would be nice. I just added the first one to the Wiki, but there's obviously many more. In case you have some rough examples and limited time, I'm willing to add them to the Wiki.

**Comment by ajb** [comment]
Thanks for adding that to the wiki. If you want to add more, I'll be most appeciative, although I had to remove the 2nd example in there, since it talks about modifying the Javascript directly.
