### ISSUE TITLE
client_side_validations.git repository not found

### ISSUE THREAD

**Issue by sylvesterwillis** [dobtco/formbuilder#48]
During the execution of 'bundle install' I came across the error 
fatal: remote error: 
  Repository not found.
Git error: command `git clone
'git://github.com/adamjacobbecker/client_side_validations.git'
"/home/swillis16/.rvm/gems/ruby-2.0.0-p353@procure-io-community/cache/bundler/git/client_side_validations-1187a622c9e045f4543925f236f53dd5ae19d343"
--bare --no-hardlinks` in directory /home/swillis16/Documents/procure-io has failed.

Was this Git repo owned by adamjacobbecker or was it a fork of another repo?

**Comment by ajb** [comment]
I'm guessing you meant to open this issue in the [Formbuilder-rb repo](https://github.com/dobtco/formbuilder-rb)? Do you mind closing it and creating it over there?

**Comment by sylvesterwillis** [comment]
Sorry about the mixup. The issue occurred in the Procure-io repo.
