### ISSUE TITLE
Use Form to Collect Data

### ISSUE THREAD

**Issue by CWSpear** [dobtco/formbuilder#51]
Is there no way with this tool to rebuild the form for actual use?

I couldn't find anything in the docs/other issues.

It seems like there should be an option to display the form for use (i.e. to collect data) and an option of where to post it. I understand we have to handle all that, but we shouldn't have to manually rebuild the form when it should be _trivial_ to do in the JavaScript since it has to build it to display it while editing anyway (I see the Ruby tool, but that's not helpful for us). Just do that, but allow you to enter values and remove the sidebar and edit UI.

Maybe you can do this and I've missed it, but it should be more obvious on the main page if you can.

**Comment by ajb** [comment]
Here's an old issue for it: https://github.com/dobtco/formbuilder/issues/21

If you want to take a crack at it, I'd be more than happy to answer any questions you may have. I agree that it should be part of the library, but at this point I can't make any promises about _when_ I could ship such a feature.
