### ISSUE TITLE
Is there a way to support multiple-columns in the same row?

### ISSUE THREAD

**Issue by jinal** [dobtco/formbuilder#60]
Wondering if anyone has modified / extended this gem to support multip-columns in the same row? Any thoughts on how complex would that be?

Thanks

**Comment by abemedia** [comment]
CSS?

**Comment by jinal** [comment]
Sure. Do you know if someone has tried it. I want to see what's the preferred layout

**Comment by abemedia** [comment]
Well if you just want a quick fix you could try something like this:

```
.fb-response-fields>* {
    float: left;
    width: 50%;
}
.fb-response-fields>*:nth-child(odd) {
    clear: both;
}
```

If however you wanted some areas in multiple columns and others not it would require grouping the fields as suggested here https://github.com/dobtco/formbuilder/issues/57

**Comment by jinal** [comment]
Got it. Thanks Adam.

On Friday, March 21, 2014, Adam Bouqdib notifications@github.com wrote:

> Well if you just want a quick fix you could try something like this:
> 
> .fb-response-fields>\* {
>     float: left;
>     width: 50%;
> }
> .fb-response-fields>*:nth-child(odd) {
>     clear: both;
> }
> 
> If however you wanted some areas in multiple columns and others not it
> would require grouping the fields as suggested here #57https://github.com/dobtco/formbuilder/issues/57
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/dobtco/formbuilder/issues/60#issuecomment-38299308
> .

## 

_Jinal Jhaveri_
(323) 839-4538
www.logn.co

http://www.linkedin.com/company/logn  https://www.facebook.com/logndotco
  http://www.twitter.com/logndotco

**Comment by codybaldwin** [comment]
jinal, I would like to know what your solution was.
