### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by pesar368** [dobtco/formbuilder#61]
How can i Save my form as html in other file?
And Save button do something in server side?

**Comment by emphilip** [comment]
Ive written something that allows for rendering the html form from form
builder and then serializes form responses into a json string. If you can
wait until tonight I can provide a link to that

**Comment by pesar368** [comment]
thank you alot  emphilip
sure Waiting

**Comment by gsxdsm** [comment]
Look forward to that also!

**Comment by pesar368** [comment]
Dear emphilip Please help us

**Comment by stephentcannon** [comment]
@emphilip can you provide details on the rendering and collection.  I was getting ready to work on a rending method and use toJSON to collect the form on submit.  I would like to see your solution before I proceed.
