### ISSUE TITLE
how to create page with two formbuilder divisions 

### ISSUE THREAD

**Issue by ksudheer** [dobtco/formbuilder#71]
IS it possible to create a page with two formbuilder divisions.
So that i can drag and drop any of the division.
One for inclusion and one for exclusion.

**Comment by ajb** [comment]
This is not possible currently. I'm a little unclear on what you mean, but I'm always happy to review PRs.

**Comment by ksudheer** [comment]
i was just trying to modify formbuilder and use it for the following requirement.
There will be two droppable divisions, one is inclusion division and another is exclusion.
Drag-drop and select the list of users categories to be included and darg-drop the and select the user categories to be excluded.
i am trying with other options..
thank you for the reply.

**Comment by ThangPk** [comment]
@ksudheer Hi, did you have any solutions for this one? I'm also interesting in this feature. Thanks you.
