### ISSUE TITLE
form builder is done, how can i use this form for my users?

### ISSUE THREAD

**Issue by nishant-befree** [dobtco/formbuilder#72]
Hello,

I got this form builder & saved that form json inside db.

now i want to load that form for general use, with validation and store form data inside my db.
how is it possible for json to HTML?

**Comment by capripio** [comment]
Well I've done this manually from php but you can do it by javascript!

**Comment by nishant-befree** [comment]
i have to use  that data with highly usage functionality,

can you please provide any example or script reference?

**Comment by capripio** [comment]
Well I am not sure what you exactly want. You can use if condition in js or switch/if condition to convert data to html

**Comment by nishant-befree** [comment]
Asif, i need data to html, how it possible?

**Comment by capripio** [comment]
static public function makeField($field) {
        switch ($field->field_type) {
            case 'section_break':
                ?>
                <tr>
                    <td colspan="2">
                        <h2 class="fcf section_break"><?php echo $field->label ?></h2>
                    </td>
                </tr>
                <?php
                break;
            case 'text':
            case 'email':
            case 'date':
            case 'time':
            case 'website':
                $req = 'required';
                if (!$field->required)
                    $req = '';
                if ($field->field_type == 'website')
                    $field->field_type = 'url';
                ?>
                <tr>
                    <td><label><?php echo $field->label ?></label></td>
                    <td><input class="fcf <?php echo $field->field_type . ' ' . $req; ?>" name="fcf[<?php echo $field->cid ?>]" type="<?php echo $field->field_type ?>" ></td>
                </tr>
                <?php
                break;
?>

**Comment by nishant-befree** [comment]
hmm, so we have to parse form JSON manually and create form

If i found whole script that it may save my lots of time

**Comment by capripio** [comment]
http://hastebin.com/koruriduro.php

**Comment by nishant-befree** [comment]
yes, this HTML helper is most useful for PHP,

Let me quite play with coffeescript, trying to add another option / control property name with "parent" where i define parent control, so while use if parent control value is true then only child control appears with option property :).

**Comment by capripio** [comment]
Well yea sure, do your art!
