### ISSUE TITLE
How to render user live view of the form data?

### ISSUE THREAD

**Issue by stephentcannon** [dobtco/formbuilder#73]
I do not think it should be the goal of form builder to handle the form http post and processing but it should have the ability to render the form from the JSON.  The default should be identical to what it looks like in the editor/builder mode.

There are 3 old issues that are similar or related to this.

https://github.com/dobtco/formbuilder/issues/21

https://github.com/dobtco/formbuilder/issues/51

https://github.com/dobtco/formbuilder/issues/72

I have not seen that there is a solution as of yet.  
1.  Is there a solution and if so what is it?
2.  If there is not, could you provide a hint or push me in the right direction and I will take a shot at it.

**Comment by stephentcannon** [comment]
Implemented formbuilder into Meteor.js.  Used Meteor.js spacebars (handlebars with live reactivity) for front end live form rendering.  This is not needed now.

**Comment by nabeelahm2** [comment]
@stephentcannon can you show me how can i use Meteor.js spacebars
