### ISSUE TITLE
edit the Id of an input 

### ISSUE THREAD

**Issue by hamzazar** [dobtco/formbuilder#79]
How I can add the id in the edit field section. So the user can enter a unique id and customize it.

**Comment by warmwaterkruik** [comment]
Easy way:

Edit the file templates/edit/label_description.html
Add the last line with the input type=text to that file.

``` html
<input type='text' data-rv-input='model.<%= Formbuilder.options.mappings.LABEL %>' />
<textarea data-rv-input='model.<%= Formbuilder.options.mappings.DESCRIPTION %>'
          placeholder='Add a longer description to this field'></textarea>

<input type='text' placeholder='field id' data-rv-input='model.<%= Formbuilder.options.mappings.ID %>' />
```

Edit main.coffee and add the line to the Formbuilder.mappings class. That object already has other fields like SIZE, UNITS etc.

``` coffeescript
mappings:
   ID: 'id'
```

Rebuild with grunt and test.

That label_description template is used in all the other fields/*.coffee files so change it there and it propagates to other.

This does not bind all event handlers btw. It also does not check if it is a valid DOM ID. 

If anyone else can elaborate on that?
