### ISSUE TITLE
Create an html output

### ISSUE THREAD

**Issue by nil2567** [dobtco/formbuilder#84]
I'm creating an html output for this plugin.

If you want it please contact me

cheers

**Comment by dougvanslembrouck** [comment]
You mean the client side form? That would be great!

**Comment by elisolero** [comment]
Hi, that's great!
can you send me the plugin for html output?
(eli.solero.web@gmail.com)

**Comment by ifriz** [comment]
Any movement on this?  I would love to see this feature as well.

**Comment by nil2567** [comment]
I have developement on this.

if you want just contact me on sandro2567@hotmail.com

cheers

**Comment by siddarth-rajavelu** [comment]
Hi nil2567,
Can you send me the Html plugin?
srajavel@uci.edu

Thanks a lot

**Comment by nil2567** [comment]
Hello mate

I’m still developping it.

It already output the html but I’m still make it better.

When I’ll finish it, I’m going to put it for sell.

Thanks

**Comment by siddarth-rajavelu** [comment]
Cool, do you have an ETA?

**Comment by nil2567** [comment]
ETA?

What is that?
