### ISSUE TITLE
Rogue Field

### ISSUE THREAD

**Issue by tommyready** [dobtco/formbuilder#90]
Hi,

I'm having an issue with a rogue field showing up in the json that isnt on the screen.  Its the medical history field that came with the demo code.  It never goes away in the save when I click save.

{"fields":[{"label":"Name","field_type":"text","required":true,"field_options":{"size":"medium"},"cid":"c6"},{"label":"Medical history","field_type":"file","required":true,"field_options":{},"cid":"c14"},{"label":"Email","field_type":"email","required":true,"field_options":{},"cid":"c29"},{"label":"Phone","field_type":"text","required":false,"field_options":{"size":"medium"},"cid":"c33"},{"label":"Message","field_type":"paragraph","required":true,"field_options":{"size":"medium"},"cid":"c37"},{"label":"Untitled","field_type":"number","required":true,"field_options":{},"cid":"c18"}]}

**Comment by tommyready** [comment]
Why is this closed?  It's still an open issue that has yet to be resolved.

**Comment by ajb** [comment]
Can you provide an isolated test case on jsfiddle? Thanks.

On Thu, Aug 14, 2014 at 11:14 AM, Tommy Ready notifications@github.com
wrote:

> Why is this closed? It's still an open issue that has yet to be resolved.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dobtco/formbuilder/issues/90#issuecomment-52196588.

## 

Adam Becker
510.928.9111
@AdamJacobBecker
