### ISSUE TITLE
Cannot include formbuilder

### ISSUE THREAD

**Issue by denndk** [dobtco/formbuilder#96]
Hi all,

I tried including formbuilder on my site.

I am getting the following error:
Uncaught TypeError: Cannot read property 'prototype' of undefined formbuilder.js:46

I included: 
backbone.js
underscore.js
rivets.js
json2.js

What is wrong? :-)

**Comment by hgarfer** [comment]
Hi.

In my case I needed to include (apart from the ones you already have):
jquery
jquery-ui
ie8-node-enum.js
jquery.scrollWindowTo.js
font-awesome.css
underscore.mixin.deepExtend.js
deep-model.js

One quick way to sort this out is to do a "bower install"
and use what you get from the generated bower_components folder.

**Comment by denndk** [comment]
Hi @hgarfer,

Thanks for the tip! I did a bower install and needed the following js:
backbone
backgone-deep-model
font-awesome
jquery.scrollwindowto
rivets
underscore
underscore.mix.in.deepextend

Thanks!
