### ISSUE TITLE
Can I trust the CID of the fields?

### ISSUE THREAD

**Issue by denndk** [dobtco/formbuilder#97]
Hi,

First of all thanks for a great formbuilder. 

I building a application which allows the user to create a form which will later be filled out. Saving the form to the database was easy, but now I am making the edit form functionality. 

The bootstrap function works well but I am in doubt about which way is the safest to update my fields. Currently I am building the update function using the generated field names (cid), something like this:

``` php
        //get Form array
        $form = json_decode($payload);
        // Get current Fields with their names eg. c18 m.m.
        $oldFormFields = $this->fields->lists('cid');
        echo "oldFormFields <br />";
        var_dump($oldFormFields);
        // Get fields in the update array
        $currentFormFields = array_pluck($form->fields, 'cid');
        echo "<br />currentFormFields <br />";
        var_dump($currentFormFields);

        // Compute our check arrays

        // new Fields must be fields that are in the new Form and not in the database
        $newFields = array_diff($currentFormFields,$oldFormFields);
        echo "<br />newFields <br />";
        var_dump($newFields);
        // Deleted fields must be fields that are in the Database but not in the form
        $deletedFields = array_diff($oldFormFields, $currentFormFields);
        echo "<br />deleteFields <br />";
        var_dump($deletedFields);
        // Updated fields must be fields that are in the Form and the database
        $updatedFields = array_intersect($currentFormFields, $oldFormFields);
        echo "<br />updatedFields <br />";
        var_dump($updatedFields);
```

But from what I could dug out of the implementation of the Formbuilder, the cid is generated from the elements index in the DOM. How likely is that to change during the editing? 

From my initial testing the cid remains during editing, but if a User deleted a field with CID 3 and then adds a new, completely different, field could this then be named with CID 3? If so I am screwed when it comes to figuring out if the field is a new one or just changed. 

Any bright ideas or thoughts on this issue?

**Comment by nuonical** [comment]
I am having this issue as well. When I save the form my first text element may have a CID of 9, but on load it could be a 2. I have no way of then manipulating the item I pulled out of storage.

**Comment by denndk** [comment]
@nuonical are you sure you are experience this on load as well? The CID is save in the payload. When I store the form in the database I store the payload from the formbuilder. This is an example
`
{"fields":[{"label":"Information omkring annoncen","field_type":"section_break","required":true,"field_options":{"description":""},"cid":"c6"}]}
`

You can see that the CID is save for each field.

**Comment by nuonical** [comment]
The CID saves just fine, but when I call 

``` javascript
New Formbuilder({ boostrapData : oFormData });
```

, the CID's of the fields are always different than what was saved. To clarify, "oFormData" is what I had saved, but if I run through the fields on the generated form the cid's are different.

Here is an example :

``` javascript

// Let's say this logs 9, 10 for two fields from data we had saved as 'oData'
$.each(oData, function (key, value) {
    console.log(value.cid);
});

// Now let's create the form from our previously saved data 
var newForm = New Formbuilder({ 
    selector: '#FormBuilder',
    boostrapData : oData 
});

// If we loop through each item, the id logged is typically 2 then 3, instead of 9 then 10
$("#FormBuilder .fb-field-wrapper").each(function () {
       console.log($(this).data("cid"))
});
```

**Comment by ajb** [comment]
CID is a property of all Backbone Models: http://backbonejs.org/#Model-cid

**Comment by denndk** [comment]
@nuonical Strange as that doesn't happen when I do it. 

@adamjacobbecker I see.. 

Is there any way to populate the fields with a unique identifier?

**Comment by ajb** [comment]
I would recommend setting a unique identifier on the server, and passing this back to the client after the fields are saved.

**Comment by raviji** [comment]
i have the same issue. I want it to be unique id. Can any one help me on this?
